### ISSUE TITLE
"division by zero" error when using aggregation + attribute columns

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#860]
I'm trying to instantiate a map that uses the following dataset:

https://cartojs-test.carto.com/tables/ne_10m_populated_places_simple/public

This is the request to Windshaft CartoDB:

```
{
  "buffersize": {
    "mvt": 0
  },
  "layers": [
    {
      "id": "L1",
      "type": "mapnik",
      "options": {
        "cartocss": "\n        #layer {\n          marker-width: 7;\n          marker-fill: ramp([population], (#ecda9a, #f7945d, #ee4d5a), jenks());\n          marker-line-color: #FFFFFF;\n        }\n      ",
        "cartocss_version": "2.1.0",
        "source": {
          "id": "S1"
        },
        "interactivity": [
          "cartodb_id",
          "population"
        ],
        "attributes": {
          "id": "cartodb_id",
          "columns": [
            "population"
          ]
        },
        "minzoom": 0,
        "aggregation": {
          "threshold": 1,
          "resolution": 4,
          "placement": "point-sample",
          "columns": {
            "population": {
              "aggregate_function": "sum",
              "aggregated_column": "pop_max"
            }
          }
        }
      }
    }
  ],
  "dataviews": {},
  "analyses": [
    {
      "id": "S1",
      "type": "source",
      "params": {
        "query": "SELECT * from \n        ne_10m_populated_places_simple\n      "
      }
    }
  ]
}
```

It's basically aggregating by `population` and also specifying `population` in `attributions.columns`.

Windshaft is returning the following error:

```
{
  "errors": [
    "division by zero"
  ],
  "errors_with_context": [
    {
      "type": "layer",
      "message": "division by zero",
      "layer": {
        "id": "L1",
        "index": 0,
        "type": "mapnik"
      }
    }
  ]
}
```

cc: @jgoizueta

**Comment by jgoizueta** [comment]
The problem is that with `attributes` present in the MapConfig options we perform a query with a zero `scale_denominator` here (in Windshaft):

https://github.com/CartoDB/Windshaft/blob/9984f55e90c82a7d8205a9d3dc44319fe5688e88/lib/windshaft/backends/attributes.js#L81

Then, the aggregated query uses the scale denominator to compute the aggregation cell size which results in 0; and the aggregation query divides by that size (`_cdb_params.res`):

```
        GROUP BY
            Floor(ST_X(_cdb_query.the_geom_webmercator)/_cdb_params.res),
            Floor(ST_Y(_cdb_query.the_geom_webmercator)/_cdb_params.res)
```

I think the easiest solution would be either to use a nonzero value (1?) iin Windshaft or change the aggregation queries to avoid the division by zero (e.g. having a minimum resolution value).

I'll give it some further thought...

**Comment by jgoizueta** [comment]
Note: for the second option we would just need to change the expression here:

https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/models/aggregation/aggregation-query.js#L134

**Comment by jgoizueta** [comment]
I think we could limit the minimum aggregation cell size to something to some geographically insignificant value like 0.15 mm (2*PI*6378137/2^38 m) which is the pixel size of zoom level 30.

**Comment by alonsogarciapablo** [comment]
Thanks @jgoizueta! 👏
