### ISSUE TITLE
Fallback to metadata when api-key not found

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft-cartodb#867]
In order to make `Auth API key` migration less painful, it'd be nice to have a fallback mechanism when there is no `Auth Apikey Key` stored in Redis. In that case, authorization will perform as usual.

Implementing this fallback allow us to put in production Auth API as soon as possible w/o being blocked until the migration is done. Furthermore, we will be able to integrate with the rest of the teams involved in project Auth API easily.

cc @javitonino

**Comment by javitonino** [comment]
We are very close to be able to pull the trigger on the migration so this may be unnecessary. On the other hand, I think it would be best if we could extensively test Auth API before pulling the trigger in the migration to all users, to avoid having to fix all users if something goes wrong. On that note, this sounds great, so we can deploy the tiler to production and test it with `team` users.

But up to you really. We are here to help, so let us know if you prefer to test in staging and then go for the user migration instead of doing this fallback.

**Comment by dgaubert** [comment]
>  it would be best if we could extensively test Auth API before pulling the trigger in the migration to all users, to avoid having to fix all users if something goes wrong.
> so we can deploy the tiler to production and test it with team users.

Those are the main goals of this issue. ;).

> We are here to help, so let us know if you prefer to test in staging and then go for the user migration instead of doing this fallback.

We are going to test it in staging as well. On the other hand, this fallback is pretty easy to implement so it could be a good safe-conduct almost for free. And of course, any help is more than welcome ;) we will reach you as soon as we need you.

**Comment by dgaubert** [comment]
Done https://github.com/CartoDB/Windshaft-cartodb/pull/877
