### ISSUE TITLE
How will we measure the impact of enabling Default Point Aggregation in Builder?

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#878]
We're planning to enable Default Point Aggregation in CARTO.js / Builder. Before we do so, we need to ensure we have a proper way to measure the impact of that change.

Are there events in Kibana that we can use to create a dashboard/graph to measure the impact of this change (eg: better rendering times for datasets with more than 100k points)? Do we need to send more events to Kibana? Can we create a graphs/dashboard to see the before and after?

cc: @dgaubert @jgoizueta I will need your help with this. Thanks!
cc: @rochoa

**Comment by dgaubert** [comment]
We don't log anything different when we use aggregation. Vector maps are aggregated by default and raster maps when required. _A priori_, it isn't easy to know when a tile was rendered using aggregation or not since all the preparation work was done during map instantiation. But definitely, we can find a way to do that. What's the desired info to have to build useful dashboards?

**Comment by dgaubert** [comment]
Closing, https://github.com/CartoDB/product/issues/30#issuecomment-404055774
